# Generated by Django 5.0.4 on 2025-03-31 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_created_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_of_good_in_basket", models.IntegerField()),
                ("image", models.ImageField(upload_to="basket_items/")),
            ],
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("adress", models.TextField(null=True)),
                ("phone_number", models.CharField(max_length=12)),
                ("email", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("good_name", models.CharField(max_length=255)),
                ("good_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("good_image", models.ImageField(upload_to="goods/")),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basket_price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "basket_items_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.basket_items",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.clients"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basket_items",
            name="good_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.goods"
            ),
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.basket"
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.clients"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_of_good", models.IntegerField()),
                ("city", models.CharField(max_length=255)),
                (
                    "good_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.goods"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                (
                    "good_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.goods"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.orders"
                    ),
                ),
                (
                    "stock_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.stock"
                    ),
                ),
            ],
        ),
    ]
