# Generated by Django 5.0.4 on 2025-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_basket_items_clients_goods_basket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
